# .github/workflows/deploy-demo.yml

name: Deploy Demo App to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'demo/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (from monorepo root)
        run: npm install

      # --- START OF THE NEW, ROBUST FIX ---
      - name: Build the demo application
        # Change to the demo directory first
        working-directory: ./demo
        run: |
          # Manually add the root node_modules/.bin to the PATH for this step.
          # This explicitly tells the runner where to find 'react-scripts'.
          export PATH=$PATH:../node_modules/.bin
          npm run build
      # --- END OF THE NEW, ROBUST FIX ---

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The path is still relative to the repository root
          path: 'demo/build' # For Create React App

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4